### ISSUE TITLE
Clairfy what you mean in this sentence

### ISSUE THREAD

**Issue by Newbytee** [bdefore/protondb-i18n#15]
During my translation of ProtonDB from English to Swedish I encountered this sentence: "These reports are published on ProtonDB pending review and used by other gamers, Valve, and developers to identify and fix games.". I don't understand it entirely. 

Two questions:
> These reports are published on ProtonDB pending review

What does the "pending review" part indicate here exactly? Pending review by other gamers, Valve, and developers?

> and developers to identify and fix games

What do they identify here? Games? I'm thinking "identify issues", but I don't see that word.

**Comment by bdefore** [comment]
That could use a rewrite it's not great even in English. As you point out there's a word missing there. It should say 'identify issues'. And at this welcome step, it's probably not worth mentioning 'pending review'. Here's my revised English sentence that I'll update to:

`Reports are published on ProtonDB to help you, Valve, and developers to help fix games.`
